SY CHOU, CW LIN modified. Add TransactionGraph, TransactionGraphQueue…
elasql/elasql pull request #10
Opened 2021-08-12 16:54 UTC by tom1236868

…, SyncRequest, TimeSync classes. Add new functionalities, including depedency graph, feature collection, transmission time synchronization. Wait for merging

2021-08-12 16:57 UTC, FrankCCCCC commented
As for complete commit message, here it is:

SY CHOU, CW LIN modified. Add TransactionGraph, TransactionGraphQueue, SyncRequest, TimeSync classes. Add new functionalities, including depedency graph, feature collection, transmission time synchronization. Wait for merging

2021-08-13 06:06 UTC, FrankCCCCC commented
![image](https://user-images.githubusercontent.com/43928493/129311887-c20f5813-5889-4a34-97f7-0fcd0b2797ea.png)

Note that, in TPartStoredProcedureTask.java, since we cannot find the definition of "stopComponentTimer("Generate plan", sinkStopTime)", the compiler will show error for the code. In order to export the jar file, we don't enable that part of code temporarily.

2021-08-16 14:50 UTC, xuan19970825 commented on src/main/java/org/elasql/cache/RemoteRecordReceiver.java
> +
This file is not related. Please undo the changes.

2021-08-16 15:29 UTC, xuan19970825 requested changes
There are some files that are not related to the change. We hope you can remove these files from the commit.
`src/main/java/org/elasql/cache/RemoteRecordReceiver.java`
`src/main/java/org/elasql/storage/tx/concurrency/ConservativeOrderedCcMgr.java`
`src/main/java/org/elasql/schedule/tpart/TPartScheduler.java`

Some codes are commented in this file, could you please tell us the reason?
`src/main/java/org/elasql/storage/tx/concurrency/ConservativeOrderedLockTable.java`

2021-08-18 07:58 UTC, SLMT approved these changes
Great! Thanks for your contribution. I will do some clean up after merging.

2021-08-18 08:47 UTC, xuan19970825 approved these changes

2021-08-20 06:23 UTC, merged