Control-based Router and Transaction Estimator
elasql/elasql pull request #23
Opened 2021-09-16 08:29 UTC by SLMT

This PR adds an API to build estimation for transactions and alters the flow of stored procedure calls to send estimation to all DB servers. I also added a router based on the estimation and a controller to control the parameters of the router.

This is unfinished yet. Here is the TODO list:

- [x] Transaction Estimation
- [x] Estimator
- [x] Path to send estimations
- [x] Router
- [ ] Actuator
- [ ] Control Parameter Update Transactions

2021-10-01 06:04 UTC, pin-yu requested changes
Good code quality and readability.
There are just a few typos.
Let's fix it and go

2021-10-01 06:04 UTC, pin-yu commented on src/main/java/org/elasql/perf/tpart/TPartPerformanceManager.java
> +			// The sequencer maintains a feature collector and a warehouse
Feature collector is removed. This comment should be revised.

2021-10-01 06:04 UTC, pin-yu commented on src/main/java/org/elasql/perf/tpart/TPartPerformanceManager.java
> +			// Hermes-Control has a control aucuator
typo `aucuator` -> `actuator`

2021-10-01 06:04 UTC, pin-yu commented on src/main/java/org/elasql/perf/tpart/control/ControlParamUpdateParamHelper.java
> +	private double[] alpha;
We could add some comments to clarify what alpha, beta, gamma are

2021-10-01 06:04 UTC, pin-yu commented on src/main/java/org/elasql/perf/tpart/control/RoutingControlActuator.java
> +		Thread.currentThread().setName("routing-control-aucuator");
typo `aucuator` -> actuator

2021-10-01 06:04 UTC, pin-yu commented on src/main/java/org/elasql/perf/tpart/metric/TpartMetricWarehouse.java
> +		return load;
wrong indentation

2021-10-01 07:58 UTC, SLMT commented
@pin-yu I fixed the issues. Please check again.

2021-10-05 00:25 UTC, pin-yu approved these changes
Looks better.
Let's merge it

2021-10-06 06:52 UTC, merged